updated to live-boot scripts 3.0~a20

diff --git a/dyneIII/live-init-scripts/scripts/live-helpers b/dyneIII/live-init-scripts/scripts/live-helpers
--- a/dyneIII/live-init-scripts/scripts/live-helpers
+++ b/dyneIII/live-init-scripts/scripts/live-helpers
@@ -1,4 +1,4 @@
-# live-initramfs helper functions, used by live-initramfs on boot and by live-snapshot
+# live-boot helper functions, used by live-boot on boot and by live-snapshot
 
 if [ ! -x "/bin/fstype" ]
 then
@@ -26,7 +26,7 @@ subdevices ()
 	sysblock=${1}
 	r=""
 
-	for dev in "${sysblock}" "${sysblock}"/*
+	for dev in "${sysblock}"/* "${sysblock}"
 	do
 		if [ -e "${dev}/dev" ]
 		then
@@ -76,12 +76,7 @@ is_supported_fs ()
 
 get_fstype ()
 {
-	if [ -x /lib/udev/vol_id ]
-	then
-		/lib/udev/vol_id -t ${1} 2>/dev/null
-	else
-		/lib/udev/blkid  -o value -s TYPE ${1} 2>/dev/null
-	fi
+	/sbin/blkid -s TYPE -o value $1 2>/dev/null
 }
 
 where_is_mounted ()
@@ -184,16 +179,13 @@ setup_loop ()
 	local encryption=${5}
 	local readonly=${6}
 
-	modprobe -q -b "${module}"
+	# the output of setup_loop is evaluated in other functions,
+	# modprobe leaks kernel options like "libata.dma=0"
+	# as "options libata dma=0" on stdout, causing serious
+	# problems therefor, so instead always avoid output to stdout
+	modprobe -q -b "${module}" 1>/dev/null
 
-	if [ -x /sbin/udevadm ]
-	then
-		# lenny
-		udevadm settle
-	else
-		# etch
-		udevsettle
-	fi
+	udevadm settle
 
 	for loopdev in ${pattern}
 	do
@@ -282,7 +274,8 @@ try_mount ()
 		then
 			fstype=$(get_fstype "${dev}")
 		fi
-		mount -t "${fstype}" -o "${opts}" "${dev}" "${mountp}" || panic "Cannot mount ${dev} on ${mountp}, fstype=${fstype}, options=${opts}"
+		mount -t "${fstype}" -o "${opts}" "${dev}" "${mountp}" || \
+		( echo "SKIPPING: Cannot mount ${dev} on ${mountp}, fstype=${fstype}, options=${opts}" > live-boot.log && return 0 )
 	fi
 }
 
@@ -304,13 +297,21 @@ find_cow_device ()
 
 	for sysblock in $(echo /sys/block/* | tr ' ' '\n' | grep -v loop | grep -v ram | grep -v fd)
 	do
+		fulldevname=$(sys2dev "${sysblock}")
+
+		if echo "${black_listed_devices}" | grep -q -w "${fulldevname}"
+		then
+			# skip this device entirely
+			break
+		fi
+
 		for dev in $(subdevices "${sysblock}")
 		do
 			devname=$(sys2dev "${dev}")
 
-			if echo "${black_listed_devices}" | grep -q "${devname}"
+			if echo "${black_listed_devices}" | grep -q -w "${devname}"
 			then
-				# skip this device enterely
+				# skip this subdevice
 				break
 			fi
 
@@ -344,8 +345,7 @@ find_cow_device ()
 				done
 			fi
 
-			#if [ "$(/lib/udev/vol_id -l ${devname} 2>/dev/null)" = "${pers_label}" ]
-			if [ "$(/lib/udev/blkid -o value -s LABEL ${devname} 2>/dev/null)" = "${pers_label}" ]
+			if [ "$(/sbin/blkid -s LABEL -o value $devname 2>/dev/null)" = "${pers_label}" ]
 			then
 				echo "${devname}"
 				return 0
@@ -361,17 +361,15 @@ find_cow_device ()
 			case "$(get_fstype ${devname})" in
 				vfat|ext2|ext3|ext4|jffs2)
 					mkdir -p "${cow_backing}"
-					if ! try_mount "${devname}" "${cow_backing}" "rw"
+					if try_mount "${devname}" "${cow_backing}" "rw"
 					then
-						break
-					fi
-
-					if [ -f "${pers_fpath}" ]
-					then
-						echo $(setup_loop "${pers_fpath}" "loop" "/sys/block/loop*")
-						return 0
-					else
-						umount ${cow_backing}
+						if [ -f "${pers_fpath}" ]
+						then
+							echo $(setup_loop "${pers_fpath}" "loop" "/sys/block/loop*")
+							return 0
+						else
+							umount ${cow_backing} > /dev/null 2>&1 || true
+						fi
 					fi
 					;;
 				*)
@@ -393,14 +391,22 @@ find_files ()
 
 	for sysblock in $(echo /sys/block/* | tr ' ' '\n' | grep -v loop | grep -v ram | grep -v fd)
 	do
+		fulldevname=$(sys2dev "${sysblock}")
+
+		if echo "${black_listed_devices}" | grep -q -w "${fulldevname}"
+		then
+			# skip this device entirely
+			break
+		fi
+
 		for dev in $(subdevices "${sysblock}")
 		do
 			devname=$(sys2dev "${dev}")
 			devfstype="$(get_fstype ${devname})"
 
-			if echo "${black_listed_devices}" | grep -q "${devname}"
+			if echo "${black_listed_devices}" | grep -q -w "${devname}"
 			then
-				# skip this device enterely
+				# skip this subdevice
 				break
 			fi
 
