some of the updates needed for dyne:II
git-svn-id: svn://dyne.org/dynebolic@164 129b00e9-8bf7-0310-bee9-bd51b64996e4

diff --git a/dyneII/taschino2/nidifica b/dyneII/taschino2/nidifica
--- a/dyneII/taschino2/nidifica
+++ b/dyneII/taschino2/nidifica
@@ -24,20 +24,12 @@
 # DYNEBOL_CRYPT=encryption algorithm (if there is one, only AES128 supported)
 
 
-#include <lib/dyne/utils.sh>
+source /lib/dyne/utils.sh
 
-if [ -e /lib/dyne/utils.sh ]; then
-    source /lib/dyne/utils.sh
-else
-    MSG="dyne shell libraries are missing"
-    echo "[!] $MSG"
-    rm -f /var/log/setup/error
-    echo "$MSG" > /var/log/setup/error
-    exit 1
-fi
-
-LODEV=7 # always choose a free one! there are 0-7
+LODEV=/dev/loop30 # always choose a free one! there are 0-7
 NESTNAME="dynebol.nst" # that's the default name, dynebolE.nst is encrypted
+
+mkdir -p /var/log/setup
 
 report_success() {
 # $1 success string
@@ -74,39 +66,34 @@ report_error() {
 ### main()
 ###
 
-notice "nidifica  - create dyne:bolic nest"
+notice "nidifica  - create dyne:II nest"
 act "(c)2003-2005 by Jaromil - RASTASOFT.org"
 act "invoked with args \"$*\" "
 act "running on `date`"
 
-OPTS=`getopt -o hvs:l:e: --long help,version,size:,loc:,encrypt: -n 'nidifica' -- "$@"`
+OPTS=`getopt -o hvp:f: --long help,version,partition:,file: -n 'nidifica' -- "$@"`
 
 eval set -- "$OPTS"
 
 while true; do
     case "$1" in
 	-h)
-	    echo " .  nidifica [-hv] [-e -s mbytes] -l location"
-	    echo " .  -v, --version print out application info"
-	    echo " .  -h, --help    print this small usage guide"
-	    echo " .  -e, --encrypt encrypt nest with algo (see man losetup)"
-	    echo " .  -s, --size    size of nest in megabytes"
-	    echo " .  -l, --loc     target location"
+	    echo " .  nidifica [-hv] [-p part ] [-f file,mbytes]"
+	    echo " .  -v, --version   print out application info"
+	    echo " .  -h, --help      print this small usage guide"
+            echo " .  -p, --partition use specified partition as nest"
+	    echo " .  -f, --file      create specified file,size as nest"
 	    exit 2
 	    ;;
 	-v)
 	    exit 2
 	    ;;
-	-s)
-	    SIZE=$2
+	-p)
+	    PARTITION=$2
 	    shift 2
 	    ;;
-	-l)
-	    LOCATION=$2
-	    shift 2
-	    ;;
-	-e)
-	    ENCRYPT=$2
+	-f)
+	    LOOPBACK=$2
 	    shift 2
 	    ;;
 	--) shift; break ;;
@@ -114,165 +101,139 @@ while true; do
     esac
 done
 
+#########################################
 # check presence of all needed parameters
 FATAL=0
-if [ -z $LOCATION ]; then
-    error "must specify location"
-    FATAL=1
+
+if [ $PARTITION ]; then
+  PART_VOL="`cat /boot/volumes | grep $PARTITION`"
+  if ! [ $PART_VOL ]; then
+     error "partition $PARTITION has not been detected"
+     FATAL=1
+  else
+     notice "nesting on partition $PART_VOL"
+  fi
 fi
 
-if [ $FATAL != 0 ]; then
+if [ $LOOPBACK ]; then
+  NSTFILE="`echo $LOOPBACK|cut -d, -f1`"
+  NSTSIZE="`echo $LOOPBACK|cut -d, -f2`"
+  if ! [ $NSTSIZE ]; then
+     error "argument of -f missing size specification"
+     error "usage: -f filename,size (in bytes)"
+     FATAL=1
+  elif [ `is_writable $NSTFILE` = false ]; then
+     error "file $NSTFILE is not writable"
+     error "cannot create nest"
+     FATAL=1
+  elif [ -e $NSTFILE ]; then
+     notice "file $NSTFILE already exists"
+     echo -n "[?] You want to overwrite the existing nest?"
+     ask_yesno 10
+     if [ $? = 1 ]; then echo " yes"
+     else
+       echo " no"
+       report_error "User aborted operation: should not overwrite existing nest"
+       exit 1
+     fi
+  fi
+fi
+
+if [ $FATAL = 1 ]; then
     report_error "nidifica called with wrong arguments, operation aborted."
-    sleep 4
     exit 1
 fi
 
-if [ $ENCRYPT ]; then
-    NESTNAME="dynebolE.nst"
-fi
-
-notice "--- nesting to $LOCATION"
-sleep 1
-
-
-
-
-    if [ -z "$SIZE" ]; then
-	report_error "missing size as argument to nidifica -m nest"
-	exit 1
-    fi
-    
-    if [ ! -x $LOCATION ]; then
-        report_error "Location $LOCATION does not exist or is not a directory"
-	exit 1
-    else
-	mkdir -p ${LOCATION}/dyne
-	NEWNEST=${LOCATION}/dyne/${NESTNAME}
-    fi
-
-    if [ -e ${NEWNEST} ]; then
-	echo -n "[?] You want to overwrite the existing nest?"
-	getkey 10
-	if [ $? != 0 ]; then # getkey returns 1 when no, 2 timeout, 0 yes
-	    echo " no"
-	    report_error "User aborted operation: should not overwrite existing nest"
-	    exit 1
-	else
-            echo " yes"
-	fi
-    fi
+## parameters ok here
+####################################################################
     
 
-    SIZE_4k=`expr \( $SIZE \* 1000 \) / 4`
-    notice "generating file of ${SIZE}Mb (${SIZE_4k} blocks of 4Kb)"
-    act "dd if=/dev/zero of=${NEWNEST} bs=4k count=$SIZE_4k"
+#### nest in a loopback file to be created
+if [ $LOOPBACK ]; then
+
+    SIZE_4k=`expr \( $NSTSIZE \* 1000 \) / 4`
+    notice "generating file of ${NSTSIZE}Mb (${SIZE_4k} blocks of 4Kb)"
+    act "dd if=/dev/zero of=${NSTFILE} bs=4k count=$SIZE_4k"
     echo -n " .  "
-    dd if=/dev/zero of=${NEWNEST} bs=4k count=${SIZE_4k}
+    dd if=/dev/zero of=${NSTFILE} bs=4k count=${SIZE_4k}
     
-    sync
-
-    
-   if [ $? -eq 0 -a -e "${NEWNEST}" ]; then
-	act "OK: `ls -l ${NEWNEST}`"
-   else
-	report_error "Error creating the nest file ${NEWNEST} : (dd if=/dev/zero of=${NEWNEST} bs=4k count=$SIZE_4k)"
+    if [ $? = 0 -a -e ${NSTFILE} ]; then
+	act "OK: `ls -l ${NSTFILE}`"
+    else
+	report_error "Error creating the nest file ${NSTFILE} : (dd if=/dev/zero of=${NSTFILE} bs=4k count=$SIZE_4k)"
 	sleep 4
 	exit 1
     fi
     
     notice "mounting loopback device"
     
-    if ! [ -z $ENCRYPT ]; then
-	# LA MADONNA E' SENZ'ALTRO UNA PUTTANA: NON C'E' ALTERNATIVA ALCUNA!
-	# 3 giorni persi a trovare una parentesi { chiusa con una )
-	# grazie ALE@INCAL ! ALEEE OOOO 29 feb 2004 //jrml+ale+ganja @ muenchen
-	act " .  using ${ENCRYPT} encryption"
-	act " .  YOU MUST INSERT YOUR ENCRYPTION PASSPHRASE NOW"
-	act " .   =====  CANNOT BE LESS THAN 20 LETTERS! ====="
-	sleep 1
-	losetup -e ${ENCRYPT} -T /dev/loop/${LODEV} ${NEWNEST}
-      # here password gets asked twice by the losetup program
-      # input from user is taken from stdin
-    else
-	losetup /dev/loop/${LODEV} ${NEWNEST}
-    fi
-
-
-
-
+    losetup ${LODEV} ${NSTFILE}
     
-    if [ $? = 0 ]; then
-	if ! [ -z $ENCRYPT ]; then
-	    act "OK, REMEMBER YOUR PASSPHRASE OR YOU WILL LOOSE"
-	    act "ALL THE DATA THAT YOU WILL PUT IN THIS NEST !"
-		# setup the encryption for the configuration file
-		# (it takes all DYNEBOL_ variables, without prefix
-		# as new settings) 
-	    NEST_CRYPT="$ENCRYPT" #QUAA
-	fi
-    else
-	report_error "Error in mounting nest loopback device : (losetup /dev/loop/${LODEV} ${NEWNEST}) with encryption set to $ENCRYPT"
-	rm ${NEWNEST}
+    if [ $? != 0 ]; then
+	report_error "Error in mounting nest loopback device : (losetup ${LODEV} ${NSTFILE})"
+	rm ${NSTFILE}
 	sleep 4
 	exit 1
     fi
     
-    sync
-    
     notice "Creating the EXT2 internal filesystem"
-    mkfs.ext2  -L "dyne:bolic nest" /dev/loop/${LODEV}
+    mkfs.ext2  -L "dyne:bolic nest" ${LODEV}
     if [ $? = 0 ]; then
 	act "OK, loopback device succesfully formatted"
     else
-	losetup -d /dev/loop/${LODEV}
-	report_error "Error formatting the nest (mkfs /dev/loop/$LODEV)"
-	rm ${NEWNEST}
+	losetup -d ${LODEV}
+	report_error "Error formatting the nest (mkfs $LODEV)"
+	rm ${NSTFILE}
 	sleep 4
 	exit 1
     fi
     
-    sync
-    
     notice "Mount the nest and populate it"
-    mkdir -p /mnt/nest
-    mount -t ext2  /dev/loop/${LODEV} /mnt/nest
+    mkdir -p /tmp/nest
+    mount -t ext2  ${LODEV} /tmp/nest
+    if [ $? != 0 ]; then
+       error "cannot mount the nest"
+       report_error "Error mounting the nest (mount -t ext2 ${LODEV} /tmp/nest)"
+       rm $NSTFILE
+       sleep 4
+       exit 1
+    fi
     
-    echo -n " .  "
-    mkdir /mnt/nest/home
-    # copy hidden files
-    cp -ra /home/.* /mnt/nest/home
-    # omit the extras directory 
-    for i in `ls /home | grep -v extras`; do
-      cp -ra /home/$i /mnt/nest/home
-    done
-    echo -n "home, "
+    mkdir -p /tmp/nest/home/luther
+    cp -ra /etc/skel/*     /tmp/nest/home/luther
+    cp -ra /etc/skel/.*    /tmp/nest/home/luther
+    chown -R luther:users  /tmp/nest/home/luther
 
-    cp -ra /etc /mnt/nest
-    echo -n "etc, "
-
-    cp -ra /var /mnt/nest
-    echo -n "var, "
-
-    mkdir /mnt/nest/tmp
-    chmod a+rwt /mnt/nest/tmp
-    echo "tmp"
+    mkdir -p /tmp/nest/root
+    cp -ra /etc/skel/*     /tmp/nest/root
+    cp -ra /etc/skel/.*    /tmp/nest/root
+    chmod -R go-rwx        /tmp/nest/root
     
-    sync
-    umount /mnt/nest
-    sync
+    cp -ra /etc /tmp/nest
+    cp -ra /var /tmp/nest
+    mkdir       /tmp/nest/tmp
+    chmod a+rwt /tmp/nest/tmp
+
+    umount /tmp/nest
     
     notice "done!"
     
-    losetup -d /dev/loop/${LODEV}
+    losetup -d ${LODEV}
     
     sync
     
     act "here is your new dyne:bolic nest:"
-    stat ${NEWNEST} | tee -a $DYNEBOLIC_LOG
+    stat ${NSTFILE} | tee -a $DYNEBOLIC_LOG
     
-    report_success "Dynebolic nest succesfully created in ${NEWNEST} :: `file ${NEWNEST}|cut -d: -f2` :: CLOSE ALL APPLICATIONS AND REBOOT TO ACTIVATE YOUR NEST!"
+    report_success "Dynebolic nest succesfully created in ${NSTFILE} :: CLOSE ALL APPLICATIONS AND REBOOT TO ACTIVATE YOUR NEST!"
     notice "REBOOT TO ACTIVATE YOUR NEW NEST!"
 
+fi # end nest in loopback
 
-sleep 5
+if [ $PARTITION ]; then
+
+  notice "nesting in partition yet to be implemented"
+
+fi
+
 exit 0
